version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  groups:
    github-actions:
      patterns:
      - '*'
  schedule:
    interval: weekly
    day: sunday
    time: 03:00
    timezone: Europe/Oslo
  cooldown:
    default-days: 7
  commit-message:
    prefix: ci(github-actions)
