name: 📝 Format Dependabot PR titles

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions: {}

jobs:
  rewrite:
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
    uses: sondresjolyst/garge/.github/workflows/dependabot-title.yml@main
